vim.keymap.set("n", "<C-s>", ":up<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>sh", ":split<CR>")
vim.keymap.set("n", "<leader>sv", ":vsplit<CR>")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<leader>sq", "<C-w>q")
vim.keymap.set("n", "<leader>tt", ":terminal<CR>")
vim.keymap.set("t", "<leader>tq", "<C-\\><C-n>:q<CR>")
vim.keymap.set("n", "<leader>ts", ":split<CR>:terminal<CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "K", "mzkJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "U", "<C-r>")
vim.keymap.set("n", "H", "^")
vim.keymap.set("n", "L", "$")
vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set({ "n", "v", "i" }, "<Up>", "<Nop>")
vim.keymap.set({ "n", "v", "i" }, "<Down>", "<Nop>")
vim.keymap.set({ "n", "v", "i" }, "<Left>", "<Nop>")
vim.keymap.set({ "n", "v", "i" }, "<Right>", "<Nop>")

vim.api.nvim_create_autocmd("FileType", {
	pattern = "man",
	callback = function()
		vim.keymap.set("n", "F", "<cmd>lua require('man').show_toc()<CR>", { buffer = true, silent = true })
	end,
})

vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
