shell /bin/fish

kitty_mod shift+ctrl

background_opacity 0.9

allow_remote_control true

scrollback_lines 10000

font_size 10

term xterm-kitty

cursor_shape beam

enable_audio_bell no

remember_window_size  yes
initial_window_width  640
initial_window_height 400

clipboard_control write-clipboard write-primary

map alt+q new_tab_with_cwd
map kitty_mod+h previous_window
map kitty_mod+l next_window
map kitty_mod+k previous_window
map kitty_mod+right resize_window narrower 4
map kitty_mod+left resize_window wider 4
map kitty_mod+up resize_window taller 4
map kitty_mod+down resize_window shorter 4
map kitty_mod+i set_tab_title
map alt+f next_layout

map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9

tab_bar_edge bottom

map ctrl+shift+n no_op

tab_bar_margin_width 2.0

tab_bar_style powerline

hide_window_decorations yes

include matugen.conf
