color_theme = "matugen"
theme_background = false
vim_keys = true
update_ms = 1000
proc_sorting = "threads"
io_mode = true
net_download = 1000
net_upload = 1001
net_auto = false
save_config_on_exit = false
