### MONITOR CONFIG
# DP-0
monitor=$monitor1, 1920x1080@239.76, 0x0, 1
# HDMI-0
monitor=$monitor2, 1920x1080@75, 1920x0, 1
# Auto (duplicate primary)
monitor = , preferred, auto, 1, mirror, $monitor1


# Toggle monitors
# TODO: Fix this (env variables not working)
bind = ALT, TAB, exec, $toggleMonitor DP-5 HDMI-A-2

