### VARS

# Scripts
$screenshotScript = ~/.config/dotfiles/scripts/gs_zipline.sh 
$rofiBrightnessLauncher = ~/.config/rofi/scripts/brightness.sh
$changeLayout = ~/.config/hypr/scripts/change_layout.sh
$toggleMonitor=~/.config/hypr/scripts/monitor_toggle.sh
$menu = $rofiLauncher

# Apps
$terminal = kitty
$fileManager = nautilus
$browser = zen-browser

### MOUSE & KEYBOARD
# Input sensitivity
input {
  sensitivity = -0.2
  accel_profile = flat
}

### General
general {
  gaps_in = 4
  gaps_out = 8
  border_size = 1
  resize_on_border = true
  
  col.inactive_border = $outline 
  col.active_border = $primary
  
  layout = master
}

### Layout
dwindle {
  pseudotile = yes
  preserve_split = yes
  special_scale_factor = 0.8
}

master {
  new_on_top=0
  mfact = 0.5

}

### Misc
misc {
    vfr = 1
    vrr = 1
    # layers_hog_mouse_focus = true
    focus_on_activate = true
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    enable_swallow = false
    swallow_regex = (foot|kitty|allacritty|Alacritty)
    
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    
    initial_workspace_tracking = false
}
