source = ~/.config/hypr/matugen.conf

$font = Inter Bold 14

general {
    hide_cursor = true
}

background {
    monitor =
    path = $image
    color = $primary

    blur_size = 4
    blur_passes = 3
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    rounding = 0
    shadow_passes = 2
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.64
    dots_center = true
    inner_color = $surface
    font_color = $on_surface_variant
    check_color = $primary
    fail_color = $error
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, 50
    halign = center
    valign = bottom
}

label {
    monitor =
    shadow_passes = 1
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    color = $on_background
    font_size = 64
    font_family = $font
    position = 0, -90
    halign = center
    valign = center
}

label {
    monitor =
    text = Hey, $USER!
    shadow_passes = 1
    color = $on_surface_variant
    font_size = 20
    font_family = $font
    position = 0, -202
    halign = center
    valign = center
}
