plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
    }
}

plugin {
csgo-vulkan-fix {
    fix_mouse = true
    vkfix-app = cs2, 1440, 1080
}
}
