# Custom
windowrule {
  name = windowrule-1
  opacity = 0.8 0.8
  match:class = ^(com.sidevesh.Luminance)$
  float = on
}

windowrule {
  name = windowrule-2
  float = on
  match:class = ^(waypaper)$
}

layerrule {
  name = layerrule-1
  no_anim = on
  match:class = ^(hyprfreeze)$
}

# Game config

windowrule {
    name = cs2-tearing
    immediate = on
    match:class = ^(cs2)$
}

windowrule {
    name = cs2-opacity
    opacity = 1.0 override 1.0 override
    match:class = ^(cs2)$
}

windowrule {
    name = steam-games-fullscreen
    fullscreen = on
    match:class = ^(steam_app_.*)$
}
