# Custom
windowrule {
  name = windowrule-1
  opacity = 0.8 0.8
  match:class = ^(com.sidevesh.Luminance)$
  match:float = 1
}

windowrule {
  name = windowrule-2
  float = on
  match:class = ^(waypaper)$
}

layerrule {
  name = layerrule-1
  no_anim = on
  match:class = ^(hyprfreeze)$
}
