#
# Matugen template for starship using a dynamic palette
#

format = """
$directory$git_branch$git_status$python$nodejs$rust$golang$php$time
$character"""

palette = 'colors'

[palettes.colors]
# Defining a color palette based on Matugen variables
color1 = '#bac3ff'
color2 = '#222c61'
color3 = '#c6c5d0'
color4 = '#1f1f25'
color5 = '#222c61'
color8 = '#bac3ff'
color9 = '#e5bad8'
error = '#ffb4ab'

# Prompt symbols
[character]
success_symbol = "[🞈](bold fg:color9)"
error_symbol = "[🞈](bold fg:error)"
vicmd_symbol = "[🞈](bold #f9e2af)"

[directory]
style = "fg:color3 bg:color4"
format = "[](fg:color1 bg:color4)[ 󰉋 ](bg:color1 fg:color2)[](fg:color1 bg:color4)[ $path ]($style)[](fg:color4)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[ $symbol ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $branch ]($style)[](fg:color4)"

[git_status]
style = "fg:color3 bg:color4"
format = '[[($all_status$ahead_behind )](fg:#color3 bg:#color4)]($style)'

[python]
symbol = "󰌠"
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[ $symbol ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $virtualenv ]($style)[](fg:color4)"

[nodejs]
symbol = ""
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[ $symbol ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $version ]($style)[](fg:color4)"

[rust]
symbol = ""
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[ $symbol ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $version ]($style)[](fg:color4)"

[golang]
symbol = ""
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[ $symbol ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $version ]($style)[](fg:color4)"

[php]
symbol = ""
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[ $symbol ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $version ]($style)[](fg:color4)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:color3 bg:color4"
format = "[](fg:color8 bg:color4)[  ](bg:color8 fg:color5)[](fg:color8 bg:color4)[ $time ]($style)[](fg:color4)"


