-- Generated by Matugen. Edit the template in ~/.config/matugen/templates instead.
require("base16-colorscheme").setup({
	base00 = "{{ colors.background.default.hex }}",
	base01 = "{{ colors.surface_container_lowest.default.hex }}",
	base02 = "{{ colors.surface_container_low.default.hex }}",
	base03 = "{{ colors.outline_variant.default.hex }}",
	base04 = "{{ colors.on_surface_variant.default.hex }}",
	base05 = "{{ colors.on_surface.default.hex }}",
	base06 = "{{ colors.inverse_on_surface.default.hex }}",
	base07 = "{{ colors.surface_bright.default.hex }}",
	base08 = "{{ colors.tertiary.default.hex | lighten: -5 }}",
	base09 = "{{ colors.tertiary.default.hex }}",
	base0A = "{{ colors.secondary.default.hex }}",
	base0B = "{{ colors.primary.default.hex }}",
	base0C = "{{ colors.tertiary_container.default.hex }}",
	base0D = "{{ colors.primary_container.default.hex }}",
	base0E = "{{ colors.secondary_container.default.hex }}",
	base0F = "{{ colors.secondary.default.hex | lighten: -10 }}",
})

local function set_highlights(groups, value)
	for _, group in ipairs(groups) do
		vim.api.nvim_set_hl(0, group, value)
	end
end

vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{ colors.primary_container.default.hex }}",
	fg = "{{ colors.on_primary_container.default.hex }}",
})

set_highlights({ "String", "@string" }, {
	fg = "{{ colors.tertiary.default.hex | lighten: -15 }}",
})

set_highlights({ "Comment", "@comment" }, {
	fg = "{{ colors.outline.default.hex }}",
	italic = true,
})

set_highlights({ "Function", "@function", "@function.method" }, {
	fg = "{{ colors.secondary.default.hex }}",
})

set_highlights({ "Keyword", "@keyword", "@keyword.function", "@keyword.repeat" }, {
	fg = "{{ colors.inverse_primary.default.hex }}",
})
